import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { cn } from "@/shared/lib/cn"
import { Header } from "@/wigets/Header"
import { ReactNode } from "react"
import { ClientProvider } from "@/app/ClientProvider"
import { NextIntlClientProvider } from "next-intl"
import { ChildrenProp } from "@/shared/ui/propsPresets"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = ChildrenProp

export default async function RootLayout(
    { children, }: Props
) {
    return <html>
        <body
            className={cn(
                geistSans.variable,
                geistMono.variable,
                "antialiased flex flex-col gap-10 items-center bg-space p-5 h-dvh"
            )}
        >
            <NextIntlClientProvider>
                <ClientProvider>
                    { children }
                </ClientProvider>
            </NextIntlClientProvider>
        </body>
    </html>
}
