import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { cn } from "@/shared/lib/cn"
import { Header } from "@/wigets/Header"
import { ReactNode } from "react"
import { NextIntlClientProvider } from "next-intl"
import { getLocale, getMessages } from "next-intl/server"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface Props {
    children: ReactNode
}

export default async function RootLayout(
    { children, }: Props
) {

    return <html>
        <body
            className={cn(
                geistSans.variable,
                geistMono.variable,
                "antialiased flex flex-col gap-10 items-center bg-space p-5"
            )}
        >
        <NextIntlClientProvider>
            <Header />
            { children }
        </NextIntlClientProvider>
        </body>
    </html>
}
